server:
  port: 7210

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food_delivery
    username: postgres
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    access-token-expiry-ms: 259200000
    refresh-token-expiry-ms: 259200000


telegram:
  bot:
    username: t.me/food_delivery_angren_bot
    token: 8499626969:AAGHMtUo3DtjO87qo4CIURF6COYb1ButLew
    webhookPath: https://0d3144c067a8.ngrok-free.app
    botPath: webhook
    allowed-updates:
      - message
      - edited_message
      - my_chat_member
      - chat_member
      - callback_query